substitutions:
  _REGION: asia-northeast1
  _SERVICE_NAME: rikiya-okawa-369
  _AR_REPOSITORY: cloud-run-source-deploy
  _IMAGE_NAME: space-portfolio
  _NEXT_PUBLIC_SITE_URL: https://rikiya-okawa-369-751547237835.asia-northeast1.run.app

steps:
  - id: Build image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:latest
      - .

  - id: Push image (commit)
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA

  - id: Push image (latest)
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:latest

  - id: Deploy to Cloud Run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --service-account=cloudrun-runtime@${PROJECT_ID}.iam.gserviceaccount.com
      - --update-secrets=BASIC_AUTH_USER=BASIC_AUTH_USER:latest,BASIC_AUTH_PASSWORD=BASIC_AUTH_PASSWORD:latest
      - --set-env-vars=NEXT_PUBLIC_SITE_URL=${_NEXT_PUBLIC_SITE_URL}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:latest

options:
  logging: CLOUD_LOGGING_ONLY
